AllCops:
  TargetRubyVersion: 2.4
Metrics/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Metrics/LineLength:
  Max: 100
  Exclude:
    - bin/**
    - Gemfile

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*
    - lib/tasks/*

Metrics/ClassLength:
  Exclude:
    - test/**/*
