dist: trusty
addons:
  chrome: stable
language: ruby
rvm:
 - 2.4
before_script:
  - yarn install
  - ls -l ./node_modules
script:
  - bin/webpack
  - RAILS_ENV=test bundle exec rails test
  - yarn test
