dist: trusty
addons:
  chrome: stable
language: ruby
rvm:
 - 2.4
before_script:
  - yarn install
  - RAILS_ENV=test bin/webpack --output-path=public/packs-test
script:
  - RAILS_ENV=test bundle exec rails test
  - yarn test
