dist: trusty
addons:
  chrome: stable
language: ruby
rvm:
 - 2.4
before_script:
  - yarn install
  - bundle exec rails webpacker:binstubs
  - ruby ./bin/webpack
script:
  - RAILS_ENV=test bundle exec rails test
  - yarn test
